max_frames: 300
max_epoch: 20
batch_size: 120
margin: 0.2

eval_frames: 400
augment: True

## Training details
trainfunc: aamsoftmax

scale: 30

lr_decay: 0.95

pretrained_model_path: baseline/pretrained/WavLM-Base+.pt
weight_finetuning_reg: 0.01
LLRD_factor: 1.0
LR_Transformer: 2e-5
LR_MMFA: 5e-3

## Loss functions
nClasses: 5994

## Load and save
save_path: ../dataset/speaker_verification/exp/avg_mask70_softmax/

## Model definition
model: baseline.spk_encoder

nOut: 256
port: 6754

# et = -inf >> at * mask_point
